/* ═══════════════════════════════════════════════════════════════════════
   CATÀLEG D'EXERCICIS  —  FITXER GENERAT, NO L'EDITIS A MÀ
   ───────────────────────────────────────────────────────────────────────
   Per a cada unitat, cada exercici hi apareix UN SOL COP, amb:
     t : títol (descripció curta)
     d : dificultat ('●○○' | '●●○' | '●●●' | '')
     i : imatges de suport (enunciat i solució), en ordre
     a : 1 si és una "activitat" numerada 1–4 i no un exercici
     p : pista (opcional). Si no hi és, l'exercici simplement no mostra
         botó de pista. S'omple a mà (o enganxant-hi el que generi la IA),
         exactament igual que la resta de camps.

   Les tasques (tasques.js) només guarden NÚMEROS. Tota la resta surt d'aquí.
   Això és el que permet que una tasca barregi exercicis de temes diferents
   i en fixi l'ordre lliurement.
   ═══════════════════════════════════════════════════════════════════════ */

const UNITATS_META = {
  'u7': {nom:'Unitat 7', subtitol:'Límits i continuïtat'},
  'u8': {nom:'Unitat 8', subtitol:'Derivades'},
  'u9': {nom:'Unitat 9', subtitol:'Aplicacions de les derivades'},
  'u10': {nom:'Unitat 10', subtitol:'Representació de funcions'},
};

const CATALEG = {

  'u7': {
      1: {t:'La suma d’infinits nombres és sempre infinita? Busca un contraexemple', d:'', i:['series/data/full-1.png'], a:1},
      2: {t:'El raonament val per a qualsevol distància, no només per als 100 m?', d:'', i:['series/data/full-1.png'], a:1},
      3: {t:'És el concepte de límit o més aviat el de límit lateral? Raona-ho', d:'', i:['series/data/full-1.png'], a:1},
      4: {t:'Terme general de la successió de distàncies i a què tendeix el seu límit', d:'', i:['series/data/full-1.png'], a:1},
     33: {t:'f(x) = 2x/(x+1): calcula lim[x²(f(x+1) − f(x))] en +∞', d:'', i:['practica/data/full-1.png']},
     34: {t:'Troba a perquè lim(√(x²+ax+1) − x) = 2', d:'', i:['practica/data/full-1.png']},
     35: {t:'Troba a perquè ((x⁴+ax³)/(2+x⁴))^((3x³+1)/(x²−2)) tendeixi a e³', d:'', i:['practica/data/full-1.png','practica/data/full-2.png']},
     36: {t:'Límits en ±∞ de f(x) = (−e^(3x)+7e^(−5x))/(2e^(−5x)−4e^(3x))', d:'', i:['practica/data/full-2.png']},
     37: {t:'Calcula el valor de lim 2^(2x/(5x²+x)) quan x → −1/5', d:'', i:['practica/data/full-2.png']},
     38: {t:'Quatre límits amb radicals i indeterminació 0/0', d:'', i:['practica/data/full-2.png']},
     39: {t:'Per a quin valor del paràmetre a existeix el límit quan x → 2?', d:'', i:['practica/data/full-2.png','practica/data/full-3.png']},
     40: {t:'Determina a i b perquè la funció a trossos sigui contínua a tots els punts', d:'', i:['practica/data/full-3.png']},
     41: {t:'Demostra que f(x) = 2cos x + 1 té almenys una arrel real a [0, π]', d:'', i:['practica/data/full-3.png']},
     42: {t:'Comprova que f(x) = 2^(x+1)−1 i g(x) = 2√(x+1) es tallen a [0, 1]', d:'', i:['practica/data/full-3.png']},
     43: {t:'f(x) = 3^(−x+2) − 4: demostra que existeix x₀ amb f(x₀) = 1', d:'', i:['practica/data/full-4.png']},
     44: {t:'A partir de les gràfiques de f, g i h, determina els límits en ±∞', d:'●○○', i:['limits-funcions/data/full-1.png'], p:'Mira cada gràfica per separat a la banda dreta (x → +∞) i a l\'esquerra (x → −∞): la corba s\'apropa a una alçada fixa (asímptota horitzontal), puja o baixa sense parar, o no s\'estabilitza? No cal calcular res, només llegir el dibuix.'},
     45: {t:'Límits en +∞ de potències, radicals i exponencials', d:'●○○', i:['limits-funcions/data/full-1.png'], p:'Pensa en qui "guanya" quan x es fa molt gran: una exponencial d\'una base més gran que 1 creix molt més de pressa que qualsevol potència de x, i una arrel creix més a poc a poc que allò que hi ha a dins. Simplifica quedant-te només amb els termes que realment dominen.'},
     46: {t:'Límits de funcions racionals en +∞ i −∞', d:'●●○', i:['limits-funcions/data/full-1.png','limits-funcions/data/full-2.png'], p:'Compara el grau del numerador amb el del denominador: si són iguals, el límit és el quocient dels coeficients del terme de grau més alt; si el numerador té grau més gran, dona infinit; si en té menys, dona 0. Per al signe a −∞, vigila si les potències són parelles o senars.'},
     47: {t:'INVENTA. Escriu una funció amb cada límit donat', d:'●●○', i:['limits-funcions/data/full-2.png'], p:'Fes-ho al revés: per a cada límit que et demanen, quina és la funció més senzilla que el produeix? Un límit finit no nul suggereix numerador i denominador del mateix grau; un límit infinit, un numerador de grau més gran (o una exponencial); un límit 0, un denominador de grau més gran. No busquis res complicat.'},
     48: {t:'Límits en ±∞ de (4x+3)/(2x²+1) i (4x²+3)/(2x²+1)', d:'●○○', i:['limits-funcions/data/full-2.png'], p:'Fixa\'t que les dues funcions comparteixen denominador (grau 2) i només canvia el grau del numerador (1 i 2, respectivament): aplica la regla de comparar graus a cadascuna i observa com aquest únic canvi altera el resultat.'},     
     49: {t:'Diferència de radicals: √(x²+x−1) − √(x²−x+2) dividit per 1/2', d:'●○○', i:['limits-funcions/data/full-2.png']},
     50: {t:'Límits de potències i exponencials: (0,7)^(3x+2), (3x−7)^(2−x)…', d:'●○○', i:['limits-funcions/data/full-2.png']},
     51: {t:'INVESTIGA. Límits en ±∞ del polinomi general, de be^x i de √(cx)', d:'●●○', i:['limits-funcions/data/full-2.png','limits-funcions/data/full-3.png']},
     52: {t:'Límits amb radicals: x − √(x²−6x) i x² − √(x²−6x) en ±∞', d:'●●○', i:['limits-funcions/data/full-3.png']},
     53: {t:'Indeterminacions 1^∞ del tipus (1 ± 3/x)^(x−1) i ^(1−x)', d:'●●○', i:['limits-funcions/data/full-3.png']},
     54: {t:'Límit de (√(x²−2x) − (x−2))/(x−2) en +∞', d:'●●○', i:['limits-funcions/data/full-3.png']},
     55: {t:'Límit de √(x⁴+3x²−2) − x² + 3 en +∞', d:'●●○', i:['limits-funcions/data/full-3.png']},
     56: {t:'Quocient de diferències de radicals: (√(x+1)−√(x−1))/(√(x+2)−√(x−2))', d:'●●○', i:['limits-funcions/data/full-3.png','limits-funcions/data/full-4.png']},
     57: {t:'Límit de (x²+1)/x − (2x⁴+3x)/(x²−1) en +∞', d:'●●○', i:['limits-funcions/data/full-4.png']},
     58: {t:'Límit de (√(x²−3x+2) − √(x²+x))/2 en +∞', d:'●●○', i:['limits-funcions/data/full-4.png']},
     59: {t:'REPTE. Troba m tal que √(x²+3x−8) − √(x²+mx+7) tendeixi a −1', d:'●●●', i:['limits-funcions/data/full-4.png']},
     60: {t:'Indeterminacions 1^∞ amb quocients de polinomis', d:'●●○', i:['limits-funcions/data/full-4.png']},
     61: {t:'MATEMÀTIQUES I… ECONOMIA. Guanys ((t+4)/(t+2))^t a llarg termini', d:'●●○', i:['limits-funcions/data/full-4.png']},
     62: {t:'Límits amb exponencials de base 3: (3^x+10)/3^(x+1) i el seu invers', d:'●●○', i:['limits-funcions/data/full-4.png','limits-funcions/data/full-5.png']},
     63: {t:'Funcions amb valor absolut a trossos i els seus límits en ±∞', d:'●●○', i:['limits-funcions/data/full-5.png']},
     64: {t:'MATEMÀTIQUES I… MEDI AMBIENT. Taca d’una erupció submarina: √(t²+5t) − t', d:'●●○', i:['limits-funcions/data/full-5.png']},
     65: {t:'MATEMÀTIQUES I… ECOSISTEMES. Profunditat de la capa de sorra i el dic', d:'●●○', i:['limits-funcions/data/full-5.png']}, 
     66: {t:'Gràfica de f(x): dona un valor aproximat a aquests límits', d:'●●○', i:['limits-punt/data/full-1.png','limits-punt/data/full-2.png'], p:'Per a cada punt que et demanen, mira si per l\'esquerra i per la dreta la gràfica s\'acosta a la mateixa alçada; si no coincideixen, dona els dos límits laterals per separat en lloc d\'un únic valor.'},
     67: {t:'Límits de f(x) = 2^(ln x) i g(x) = 3^(ln(x−1)) en punts concrets', d:'●●○', i:['limits-punt/data/full-2.png']},
     68: {t:'Gràfica de g(x): valor aproximat dels límits en punts i en ±∞', d:'●●○', i:['limits-punt/data/full-2.png'], p:'Igual que amb f: comprova els límits laterals a cada punt marcat i, per a ±∞, fixa\'t cap a on tendeix la corba pels dos extrems del dibuix (puja, baixa o s\'estabilitza en una alçada).'},
     69: {t:'INVENTA. Escriu una funció amb cada límit en un punt', d:'●●○', i:['limits-punt/data/full-2.png']},
     70: {t:'Límits de f(x) = 3x/√(x²+1) en x→3, x→−1 i x→0', d:'●●○', i:['limits-punt/data/full-2.png'], p:'Comprova que √(x²+1) mai és zero: la funció és contínua a tot arreu, així que en cada punt només cal substituir directament el valor de x, sense cap indeterminació.'},
     71: {t:'Límits de f(x) = log₂(x−3) + 1 en x→4, x→7 i x→7/2', d:'●●○', i:['limits-punt/data/full-2.png']},
     72: {t:'MATEMÀTIQUES I… ECONOMIA. Valor d’una empresa: límits laterals', d:'●●○', i:['limits-punt/data/full-3.png']},
     73: {t:'Límits de g(x) = 1/(x−2) + log_(1/2)x en x→1/4 i x→8', d:'●●○', i:['limits-punt/data/full-3.png']},
     74: {t:'Límits de (6x−12)/(x²−3x−4) en 0, −1, 1 i 4', d:'●●○', i:['limits-punt/data/full-3.png']},
     75: {t:'Operacions amb límits: quins casos són indeterminacions?', d:'●●○', i:['limits-punt/data/full-3.png']},
     76: {t:'Límits de funcions racionals amb indeterminació 0/0', d:'●○○', i:['limits-punt/data/full-4.png'], p:'Quan en substituir surt 0/0, factoritza numerador i denominador (factor comú o Ruffini) per trobar l\'arrel que els anul·la, simplifica i torna a substituir.'},
     77: {t:'Opera i troba el límit en cada cas', d:'●○○', i:['limits-punt/data/full-4.png','limits-punt/data/full-5.png']},
     78: {t:'Límits amb radicals en els punts indicats', d:'●○○', i:['limits-punt/data/full-5.png']},
     79: {t:'Límits amb radicals: racionalitzar numerador o denominador', d:'●○○', i:['limits-punt/data/full-5.png','limits-punt/data/full-6.png']},
     80: {t:'Límits d’una racional de tercer grau en 4 punts i en ±∞', d:'●○○', i:['limits-punt/data/full-6.png']},
     81: {t:'Límits de f(x) = (x³−x)/(√(x²+3)−2x²) en punts i en ±∞', d:'●○○', i:['limits-punt/data/full-6.png','limits-punt/data/full-7.png']},
     82: {t:'Límits amb arrels d’índexs diferents', d:'●○○', i:['limits-punt/data/full-7.png']},
     83: {t:'Límits amb potències i indeterminació 1^∞ en un punt', d:'●○○', i:['limits-punt/data/full-7.png','limits-punt/data/full-8.png']},
     84: {t:'Límits de (cos²x)^(1/sin x) i (2x+1)^(1/x) en x→0', d:'●●○', i:['limits-punt/data/full-8.png']},
     85: {t:'Determina a perquè (x²−ax+3)/(x−3) tingui límit finit en x→3', d:'●○○', i:['limits-punt/data/full-8.png']},
     86: {t:'Determina m perquè es compleixin dues igualtats amb límits 1^∞', d:'●○○', i:['limits-punt/data/full-8.png']},
     87: {t:'Troba a perquè √(x²−ax) − √(x²+2) tendeixi a 3', d:'●●○', i:['limits-punt/data/full-8.png']},
     88: {t:'Límits d’una funció a trossos en x→−1, x→3 i x→+∞', d:'●●○', i:['limits-punt/data/full-8.png'], p:'Com que la funció és a trossos, en x=−1 i x=3 calcula per separat el límit amb l\'expressió que val a l\'esquerra i la que val a la dreta de cada punt; en +∞ fixa\'t només en el tros vàlid per a x grans.'},
     89: {t:'REPTE. A partir de lim(sin x)/x = 1, calcula límits trigonomètrics', d:'●●●', i:['limits-punt/data/full-8.png','limits-punt/data/full-9.png']},
     90: {t:'Funció a trossos: límits en 4 punts i en ±∞', d:'●●○', i:['limits-punt/data/full-9.png'], p:'Igual que en l\'exercici anterior: identifica quin tros s\'aplica a cada banda dels 4 punts de canvi i calcula els límits laterals per separat; per a ±∞ mira només el tros vàlid per a x molt grans o molt petites.'},
     91: {t:'INVENTA. Dibuixa una gràfica que compleixi 4 condicions de límit', d:'●●○', i:['limits-punt/data/full-9.png']},
     92: {t:'Sis gràfiques: són contínues en els punts indicats? Quin tipus de discontinuïtat?', d:'●●○', i:['continuitat/data/full-1.png','continuitat/data/full-2.png']},
     93: {t:'Continuïtat de 8 funcions: radicals, logaritmes i valor absolut', d:'●●○', i:['continuitat/data/full-3.png']},
     94: {t:'En quins punts hi ha discontinuïtat i de quin tipus? (6 racionals)', d:'●●○', i:['continuitat/data/full-3.png','continuitat/data/full-4.png']},
     95: {t:'f(x) = (x²−x−2)/(2−x): tipus de discontinuïtat i redefinició contínua', d:'●●○', i:['continuitat/data/full-4.png']},
     96: {t:'f(x) = (18−6√(x+5))/(x−4): on no és contínua i com fer-la contínua', d:'●●○', i:['continuitat/data/full-5.png']},
     97: {t:'f(x) = (3x³−2x²+x)/(4x): discontinuïtat evitable i nova funció', d:'●●○', i:['continuitat/data/full-5.png']},
     98: {t:'Diferències entre y = 2x−1 i y = (2x−1)(x+2)/(x+2)', d:'●●○', i:['continuitat/data/full-5.png']},
     99: {t:'Continuïtat en x→−1, x→0 i x→3 de dues funcions a trossos', d:'●●○', i:['continuitat/data/full-5.png','continuitat/data/full-6.png']},
    100: {t:'f(x) = (√(x+1)−1)/x: defineix f(0) perquè sigui contínua', d:'●●○', i:['continuitat/data/full-6.png']},
    101: {t:'Continuïtat en x→2 de f(x) = (√(x²+5)−3)/(2−x)', d:'●○○', i:['continuitat/data/full-6.png']},
    102: {t:'Continuïtat en x→−1 i x→2 d’una funció a trossos amb logaritme', d:'●●○', i:['continuitat/data/full-6.png']},
    103: {t:'Analitza la continuïtat d’una funció a trossos amb exponencial', d:'●●○', i:['continuitat/data/full-6.png','continuitat/data/full-7.png']},
    104: {t:'Funcions amb valor absolut: expressa-les a trossos i estudia la continuïtat', d:'●●○', i:['continuitat/data/full-7.png','continuitat/data/full-8.png']},
    105: {t:'INVESTIGA. f(x) = |P(x)/(x−a)|: on és contínua i quines discontinuïtats té', d:'●●○', i:['continuitat/data/full-8.png']},
    106: {t:'Calcula a i b perquè dues funcions a trossos siguin contínues', d:'●●○', i:['continuitat/data/full-8.png']},
    107: {t:'Completa la funció perquè sigui contínua en x = 2', d:'●●○', i:['continuitat/data/full-8.png']},
    108: {t:'Calcula a i b: funcions a trossos amb radicals i trigonomètriques', d:'●●○', i:['continuitat/data/full-8.png','continuitat/data/full-9.png']},
    109: {t:'Troba a perquè cadascuna de 8 funcions a trossos sigui contínua', d:'●●○', i:['continuitat/data/full-9.png','continuitat/data/full-10.png']},
    110: {t:'Bolzano en 8 funcions definides per trossos, a [0,3]', d:'●●○', i:['bolzano/data/full-1.png','bolzano/data/full-2.png']},
    111: {t:'f(x) = √x + ln x − 2: existeix a amb f(a) = 0', d:'●●○', i:['bolzano/data/full-2.png']},
    112: {t:'f(x) = eˣ⁻² + x − 5: arrel en un interval de longitud 1/2', d:'●●○', i:['bolzano/data/full-2.png','bolzano/data/full-3.png']},
    113: {t:'Arrel real de x³ + 6x² + 12x + 9 = 0; interval de longitud 2', d:'●●○', i:['bolzano/data/full-3.png']},
    114: {t:'Arrel de x³ + 3x² + x = 0 a [−3,−2], error < 0,1', d:'●●○', i:['bolzano/data/full-3.png']},
    115: {t:'Matemàtiques i... Dopatge: detectabilitat en sang', d:'●●○', i:['bolzano/data/full-3.png']},
    116: {t:'MATEMÀTIQUES I… PRÉSTECS BANCARIS. Fórmula de la TAE amb interès continu', d:'●●○', i:['problemes-limits/data/full-1.png','problemes-limits/data/full-2.png']},
    117: {t:'MATEMÀTIQUES I… MEDICINA. Creixement d’un virus i evolució a llarg termini', d:'●●○', i:['problemes-limits/data/full-2.png']},
    118: {t:'Teorema de Bolzano: prova que una equació té almenys dues arrels reals', d:'●●○', i:['problemes-limits/data/full-2.png']},
    119: {t:'MATEMÀTIQUES I… INFORMÀTICA. Llei d’Amdahl i guany màxim de velocitat', d:'●●○', i:['problemes-limits/data/full-2.png','problemes-limits/data/full-3.png']},
    120: {t:'f(x) = x+1 talla e^(x−1), x³+3x i ln x+3: aproxima el punt de tall', d:'●●○', i:['problemes-limits/data/full-3.png']},
    121: {t:'f(x) = 2sin x i g(x) = −3x+1 es tallen: interval més petit que π/2', d:'●●○', i:['problemes-limits/data/full-4.png']},
    122: {t:'REPTE. f(x) = e^(x³−5x+1) pren els valors e, e², …, e¹⁰ a [2, 3]', d:'●●●', i:['problemes-limits/data/full-4.png']},
    123: {t:'MATEMÀTIQUES I… ECONOMIA. Ingressos i despeses: instant sense beneficis', d:'●●○', i:['problemes-limits/data/full-4.png']},
    124: {t:'Teorema de Weierstrass: màxim i mínim absoluts a l’interval [0, 5]', d:'●●○', i:['problemes-limits/data/full-4.png']},
    125: {t:'REPTE. f(x) = x·sin(πx/4): existeix α a (0,4) amb f(α) = f(α+1)', d:'●●●', i:['problemes-limits/data/full-4.png']},
    126: {t:'h(t) = t(20−2t)/100: calcula h(2) i troba a > 0 tal que h(a) = 0', d:'', i:['problemes-diversos/data/full-1.png','problemes-diversos/data/full-2.png']},
    127: {t:'La mateixa funció com a alçada d’una inflor: durada del període', d:'', i:['problemes-diversos/data/full-2.png']},
    128: {t:'f(x) = (11x+17)/(2x+12): límits en x→1, en un punt a i en +∞', d:'', i:['problemes-diversos/data/full-2.png']},
    129: {t:'La mateixa funció com a muntatges diaris d’un treballador', d:'', i:['problemes-diversos/data/full-2.png']},
    130: {t:'f(x) = x³/4 − 3x²/2 + 6: valors f(0) i f(4), i tall amb l’eix X', d:'', i:['problemes-diversos/data/full-2.png']},
    131: {t:'La mateixa funció com a trajectòria d’un mascarell que caça un peix', d:'', i:['problemes-diversos/data/full-2.png','problemes-diversos/data/full-3.png']},
  },

  'u8': {
      1: {t:'Busca situacions quotidianes on hi hagi present la llei de Newton del refredament', d:'', i:['mon-real/data/full-1.png','mon-real/data/full-2.png'], a:1},
      2: {t:'Defineix amb les teves paraules què és el punt d\'equilibri tèrmic i com s\'hi arriba', d:'', i:['mon-real/data/full-2.png'], a:1},
      3: {t:'Què passarà amb la temperatura de l\'objecte i de l\'ambient a mesura que creixi el temps?', d:'', i:['mon-real/data/full-2.png'], a:1},
      4: {t:'Busca altres contribucions d\'Isaac Newton més enllà de la gravitació universal', d:'', i:['mon-real/data/full-2.png'], a:1},
     21: {t:'Recta tangent a la gràfica de f(x) = x·ln x en x = e', d:'', i:['practica/data/full-1.png']},
     22: {t:'f(x) = 3x³ + 2: punts amb tangent paral·lela a la bisectriu del primer quadrant', d:'', i:['practica/data/full-1.png']},
     23: {t:'y = −x + 1 tangent a f(x) = (a − 1)sin x + bx en x = π: determina a i b', d:'', i:['practica/data/full-1.png']},
     24: {t:'Continuïtat i derivabilitat de la funció a trossos x² − 4x + 3 / −x² + 4x − 3', d:'', i:['practica/data/full-1.png']},
     25: {t:'Valors d\'a perquè la funció a trossos amb sin(ax) sigui contínua; derivabilitat', d:'', i:['practica/data/full-1.png','practica/data/full-2.png']},
     26: {t:'Regla de la cadena amb f(x) = tg(x² + 1) i g(x) = 2eˣ: (g∘f), (f∘g) i (f∘f)', d:'', i:['practica/data/full-2.png']},
     27: {t:'h derivable amb h(1) = 3 i h′(1) = 2: calcula f′(1) de f(x) = x·ln h(x) + h²(x)/x', d:'', i:['practica/data/full-2.png']},
     28: {t:'Derivada de f(x) = (tg x)^(x+3) per derivació logarítmica', d:'', i:['practica/data/full-3.png']},
     29: {t:'Recta tangent a la circumferència de centre C(1, 1) que passa per A(3, 3)', d:'', i:['practica/data/full-3.png']},
     30: {t:'TVM de f(x) = 7x − 4 en quatre intervals', d:'●○○', i:['derivada-punt/data/full-1.png']},
     31: {t:'TVM en [2, 3] de tres funcions: constant, afí i lineal', d:'●○○', i:['derivada-punt/data/full-1.png']},
     32: {t:'TVM de f(x) = 3/(x + 2) en [1, 6] i [1, 4] i derivada en x = 1', d:'●○○', i:['derivada-punt/data/full-1.png','derivada-punt/data/full-2.png']},
     33: {t:'Calcula b perquè la TVM de f(x) = ln(x + b) en [0, 2] valgui ln 2', d:'●○○', i:['derivada-punt/data/full-2.png']},
     34: {t:'s(t) = 3t² + t + 2: velocitat mitjana del mòbil en els 6 primers segons', d:'●○○', i:['derivada-punt/data/full-2.png']},
     35: {t:'TVM de la superfície d\'un cercle en passar el radi d\'1 a 3 cm i de 3 a 5 cm', d:'●○○', i:['derivada-punt/data/full-2.png','derivada-punt/data/full-3.png']},
     36: {t:'Matemàtiques i… caiguda lliure: TVM i derivada de h = 5t²', d:'●○○', i:['derivada-punt/data/full-3.png']},
     37: {t:'Derivada per definició de quatre funcions en el punt indicat', d:'●○○', i:['derivada-punt/data/full-3.png']},
     38: {t:'Derivada per definició en x₀ = 0 de quatre polinomis amb paràmetres', d:'●●○', i:['derivada-punt/data/full-3.png','derivada-punt/data/full-4.png']},
     39: {t:'Derivada en x = 2, si és possible, de sis funcions amb radicals i valor absolut', d:'●●○', i:['derivada-punt/data/full-4.png']},
     40: {t:'Recta tangent a la paràbola f(x) = x² − 2x − 3 en x = 2 i representació gràfica', d:'●○○', i:['interpretacio-geometrica/data/full-1.png']},
     41: {t:'Recta tangent a f(x) = x² − ax + 6 en el punt P(1, 2)', d:'●○○', i:['interpretacio-geometrica/data/full-1.png']},
     42: {t:'Recta tangent a ln(3x + 1), 2 + cos x i 1 + √(2 − x) en el punt indicat', d:'●○○', i:['interpretacio-geometrica/data/full-1.png']},
     43: {t:'Inventa: dues funcions amb la recta tangent donada en x = 2', d:'●●○', i:['interpretacio-geometrica/data/full-2.png']},
     44: {t:'Rectes tangent i normal a f(x) = ln√(2x + 3) en x = −1', d:'●○○', i:['interpretacio-geometrica/data/full-2.png']},
     45: {t:'Recta tangent a f(x) = e⁴ˣ⁺² − 3 en x = −1/2', d:'●○○', i:['interpretacio-geometrica/data/full-2.png']},
     46: {t:'Rectes tangent i normal a f(x) = (x − 2)/(x + 1) al tall amb l\'eix d\'abscisses', d:'●●○', i:['interpretacio-geometrica/data/full-2.png']},
     47: {t:'Recta tangent a f(x) = √((x² − 5)/(4 − x)) en el punt d\'abscissa x = 3', d:'●●○', i:['interpretacio-geometrica/data/full-2.png']},
     48: {t:'Rectes tangent i normal a y = x³ + x² − 6x + 1 al punt d\'ordenada 1 i abscissa positiva', d:'●●○', i:['interpretacio-geometrica/data/full-2.png']},
     49: {t:'Tangent a y = x² − 2x + 5 paral·lela a la secant pels punts d\'abscissa 1 i 3', d:'●●○', i:['interpretacio-geometrica/data/full-2.png','interpretacio-geometrica/data/full-3.png']},
     50: {t:'Investiga: pot y = 2x − m ser tangent a f(x) = eˣ − x² − 2?', d:'●●●', i:['interpretacio-geometrica/data/full-3.png']},
     51: {t:'Tangent a f(x) = ln(x − 1) paral·lela a la secant a l\'interval [2, e + 1]', d:'●●○', i:['interpretacio-geometrica/data/full-3.png']},
     52: {t:'Troba b i c perquè y = x² + bx + c tingui a (1, 1) tangent paral·lela a la bisectriu', d:'●●○', i:['interpretacio-geometrica/data/full-3.png']},
     53: {t:'y = x² − 2x − 3: tangent que forma 45° amb l\'eix X i tangent horitzontal', d:'●●○', i:['interpretacio-geometrica/data/full-3.png']},
     54: {t:'f(x) = x³ − x + 4: punts amb tangent paral·lela a y = 2x − 123', d:'●●○', i:['interpretacio-geometrica/data/full-4.png']},
     55: {t:'Troba k perquè les tangents a kx³ − x² + 7kx − 18 en x = 1 i x = 2 siguin paral·leles', d:'●●○', i:['interpretacio-geometrica/data/full-4.png']},
     56: {t:'Calcula a perquè la tangent a f(x) = −ax² + 5x − 4 en x = 3 talli l\'eix X en x = 5', d:'●●○', i:['interpretacio-geometrica/data/full-4.png']},
     57: {t:'f(x) = √(x² + m): troba m per tangència amb 2x − y − 3 = 0 i per pas per Q(1, 1)', d:'●●○', i:['interpretacio-geometrica/data/full-4.png','interpretacio-geometrica/data/full-5.png']},
     58: {t:'Àrea del triangle que la tangent a f(x) = (x + 1)/(x − 1) en x = 2 forma amb els eixos', d:'●●○', i:['interpretacio-geometrica/data/full-5.png']},
     59: {t:'Àrea del triangle delimitat pels eixos i la tangent a f(x) = √(x² + 5) en x = 2', d:'●●○', i:['interpretacio-geometrica/data/full-5.png']},
     60: {t:'Àrea delimitada pels eixos i la tangent a f(x) = 3 + ln(tg x) en x = π/4', d:'●●○', i:['interpretacio-geometrica/data/full-5.png']},
     61: {t:'Repte: àrea del triangle format per les tangents en x = −2 i x = 5 i l\'eix d\'abscisses', d:'●●●', i:['interpretacio-geometrica/data/full-5.png','interpretacio-geometrica/data/full-6.png']},
     62: {t:'f(x) = (x + 1)eˣ: tangent i normal al tall amb l\'eix X i àrea del triangle', d:'●●●', i:['interpretacio-geometrica/data/full-6.png']},
     63: {t:'Repte: f(x) = x² + ax + b i g(x) = c·e⁻⁽ˣ⁺¹⁾ amb la mateixa tangent a P(−1, 2)', d:'●●●', i:['interpretacio-geometrica/data/full-6.png']},
     64: {t:'Recta tangent a x² + 16y² − 16 = 0 en el punt d\'abscissa 3 i ordenada positiva', d:'●●○', i:['interpretacio-geometrica/data/full-6.png']},
     65: {t:'Repte: àrea delimitada pels eixos i les tangents a la circumferència de radi √5 en x = 1', d:'●●●', i:['interpretacio-geometrica/data/full-6.png','interpretacio-geometrica/data/full-7.png']},
     66: {t:'Determina a, b, c i d de f(x) = ax³ + bx² + cx + d amb dues condicions de tangència', d:'●●●', i:['interpretacio-geometrica/data/full-7.png']},
     67: {t:'Derivades laterals per definició de √(x + 1) i √(x − 1) en x = 1', d:'●●○', i:['derivabilitat/data/full-1.png','derivabilitat/data/full-2.png']},
     68: {t:'Expressa |x − 3| − 1 i x − |9 − x²| a trossos i calcula\'n les derivades laterals en x = 3', d:'●●○', i:['derivabilitat/data/full-2.png']},
     69: {t:'Derivades laterals per definició de la funció a trossos 4 − x − x² / 3x + 4 en x = −2', d:'●●○', i:['derivabilitat/data/full-2.png']},
     70: {t:'Derivades laterals per definició de f(x) = 1/x, amb f(0) = 0, en x = 0', d:'●●○', i:['derivabilitat/data/full-2.png']},
     71: {t:'Continuïtat i derivabilitat de la funció a trossos −1 / x + 2 / 8/x', d:'●●○', i:['derivabilitat/data/full-2.png','derivabilitat/data/full-3.png']},
     72: {t:'Continuïtat i derivabilitat de dues funcions a trossos amb cos x i sin x', d:'●●○', i:['derivabilitat/data/full-3.png']},
     73: {t:'Continuïtat i derivabilitat a l\'interval [−2, 5] d\'una funció racional i radical', d:'●●○', i:['derivabilitat/data/full-3.png','derivabilitat/data/full-4.png']},
     74: {t:'Investiga: continuïtat i derivabilitat de f(x) = a − |2x − 6|', d:'●●○', i:['derivabilitat/data/full-4.png']},
     75: {t:'f(x) = |x|³ + x + 1 a trossos: és contínua i derivable? I g(x) = |x|³ + |x| + 1?', d:'●●○', i:['derivabilitat/data/full-4.png']},
     76: {t:'Inventa: una funció contínua i no derivable en x = 5', d:'●●○', i:['derivabilitat/data/full-4.png']},
     77: {t:'Determina a perquè la funció a trossos cos x / x² + a sigui derivable en x = 0', d:'●●○', i:['derivabilitat/data/full-5.png']},
     78: {t:'Determina a i b perquè x² / a + bx / 3 sigui contínua; estudia\'n la derivabilitat', d:'●●○', i:['derivabilitat/data/full-5.png']},
     79: {t:'Calcula m i n perquè √(25 − x²) / x² + mx + n sigui derivable en x = 4', d:'●●○', i:['derivabilitat/data/full-5.png','derivabilitat/data/full-6.png']},
     80: {t:'f(x) = 1 + a√(x+1)·ln(x+1) / (x−1)²: contínua per a tot a, i valor d\'a que la fa derivable', d:'●●○', i:['derivabilitat/data/full-6.png']},
     81: {t:'Troba a, b i c perquè dues funcions de tres branques siguin contínues i derivables en ℝ', d:'●●●', i:['derivabilitat/data/full-6.png','derivabilitat/data/full-7.png']},
     82: {t:'Troba a i b perquè ln(e + sin x) / x³ + ax + b sigui derivable en x = 0', d:'●●○', i:['derivabilitat/data/full-7.png']},
     83: {t:'Troba a i b perquè ax² + bx + 1 / a² − sin x sigui contínua i derivable en tot ℝ', d:'●●○', i:['derivabilitat/data/full-7.png']},
     84: {t:'Calcula a i b perquè dues funcions amb exponencial i radical siguin derivables en ℝ', d:'●●○', i:['derivabilitat/data/full-7.png','derivabilitat/data/full-8.png']},
     85: {t:'Repte: paràmetres de x² + a(x+b) / log₂(x+2) i àrea amb la tangent en x = 3', d:'●●●', i:['derivabilitat/data/full-8.png']},
     86: {t:'Derivada de sis funcions elementals: x² − 5, 5ln x, sin 2x, e⁻ˣ, 2³ˣ i log₂x', d:'●○○', i:['funcio-derivada/data/full-1.png']},
     87: {t:'Funció derivada per definició de 123, 3x², x³ i ax', d:'●○○', i:['funcio-derivada/data/full-1.png']},
     88: {t:'Derivada per definició de −5/x, √x, x² + 2x i ax²', d:'●●○', i:['funcio-derivada/data/full-1.png']},
     89: {t:'Derivades successives de x⁴, sin x, cos x i ln x', d:'●○○', i:['funcio-derivada/data/full-1.png']},
     90: {t:'f(x) = 2^cos(g(x)): calcula f′(π) sabent que g(π) = π/2 i g′(π) = −2', d:'●○○', i:['funcio-derivada/data/full-1.png','funcio-derivada/data/full-2.png']},
     91: {t:'Investiga: derivada n-èsima de √x, sin 2x, e⁻ˣ, 2ˣ, xeˣ i cos²x', d:'●●○', i:['funcio-derivada/data/full-2.png']},
     92: {t:'Derivada de 3√x + 1/x i de 2ln x − 5/x + 6', d:'●○○', i:['funcio-derivada/data/full-2.png']},
     93: {t:'Derivada de x²·∛x, x²e^(x+2), 2x⁴cos x i √(cos x)·sin x', d:'●○○', i:['funcio-derivada/data/full-2.png']},
     94: {t:'Propietats de les derivades: sis quocients amb radicals, exponencials i potències', d:'●●○', i:['funcio-derivada/data/full-2.png','funcio-derivada/data/full-3.png']},
     95: {t:'Derivada amb arctg, sec i arccos, i productes trigonomètrics', d:'●●○', i:['funcio-derivada/data/full-3.png']},
     96: {t:'Inventa: dues funcions amb derivada f′(x) = −cos(2x)', d:'●●○', i:['funcio-derivada/data/full-3.png']},
     97: {t:'Derivada de ln(x⁴ − 3x³), ln√(2x² − 4), x/ln x i log₂(5x³ − 1)', d:'●●○', i:['funcio-derivada/data/full-3.png']},
     98: {t:'Derivada de logaritmes composts: ln(tg 2x), ln[cos(x² − 1)]³ i quocients', d:'●●○', i:['funcio-derivada/data/full-3.png']},
     99: {t:'Deu derivades a simplificar al màxim: 4ˣ, quocients, radicals i productes', d:'●●○', i:['funcio-derivada/data/full-3.png','funcio-derivada/data/full-4.png']},
    100: {t:'Sis derivades a simplificar: quocients amb eˣ, ln x i radicals', d:'●●○', i:['funcio-derivada/data/full-4.png']},
    101: {t:'Regla de la cadena: 3^(x²+4), (x⁵ − 2)³, arrels, e^(−x²), sin²x i 2^sin x', d:'●●○', i:['funcio-derivada/data/full-4.png']},
    102: {t:'Inventa: dues funcions amb derivada f′(x) = −2sin(2x)·e^cos(2x)', d:'●●○', i:['funcio-derivada/data/full-5.png']},
    103: {t:'Derivada d\'arcsin(1/x), cos(x² + 5x + 5), cotg x/x² i arcsin(5x + 1)', d:'●●○', i:['funcio-derivada/data/full-5.png']},
    104: {t:'Derivada de 12√(3x² + x), ln(sin x²) i (4x² − 5x + 1)·3ˣ', d:'●●○', i:['funcio-derivada/data/full-5.png']},
    105: {t:'Derivada de tg²(2x + 3), arctg(x³ + 6), radicals i 2x·arcsin x', d:'●●○', i:['funcio-derivada/data/full-5.png']},
    106: {t:'Derivada d\'arctg(2/x²), ln(√sin x), tg²(cos 2x) i arcsin√(1 − 4x²)', d:'●●○', i:['funcio-derivada/data/full-5.png']},
    107: {t:'Repte: g(x) = √(e^(−3x²)) i f(x) = cos²(g(x)) + sin²(g(x)); calcula f′(π/6)', d:'●●●', i:['funcio-derivada/data/full-6.png']},
    108: {t:'Derivada de sin(2x)·e^cos(2x), tg²(1 − 5x), cos(2x − 1)³ i cos³(2x − 1)', d:'●●○', i:['funcio-derivada/data/full-6.png']},
    109: {t:'Derivada de vuit quocients amb eˣ, arctg, ln i funcions trigonomètriques', d:'●●○', i:['funcio-derivada/data/full-6.png']},
    110: {t:'Investiga: derivada de f(x) = x^(xˣ) per derivació logarítmica', d:'●●○', i:['funcio-derivada/data/full-6.png']},
    111: {t:'Derivada de nou funcions amb logaritmes, radicals i quocients trigonomètrics', d:'●●○', i:['funcio-derivada/data/full-6.png','funcio-derivada/data/full-7.png']},
    112: {t:'Regla de la cadena amb composicions de ln, arccos, tg i arcsin', d:'●●●', i:['funcio-derivada/data/full-7.png']},
    113: {t:'Derivada de deu funcions amb arcsin, arctg, arccos i logaritmes', d:'●●○', i:['funcio-derivada/data/full-7.png','funcio-derivada/data/full-8.png']},
    114: {t:'Derivada de ln√((x+1)/(x−1)), arctg, arccos(ln x), ∛(2^cos x) i log₂', d:'●●○', i:['funcio-derivada/data/full-8.png']},
    115: {t:'Derivada de quatre expressions amb ln, tg i quocients trigonomètrics', d:'●●●', i:['funcio-derivada/data/full-8.png']},
    116: {t:'Investiga: derivada de (cos x + cos(x+1))/(sin x − sin(x+1)); és constant?', d:'●●●', i:['funcio-derivada/data/full-8.png']},
    117: {t:'Derivada d\'arctg√((1 − sin x)/(1 + sin x)) simplificant al màxim', d:'●●○', i:['funcio-derivada/data/full-8.png','funcio-derivada/data/full-9.png']},
    118: {t:'Derivació logarítmica: (√x)ˣ, x^√x, (sin x)^2x, ˣ√(cos x) i (arcsin x)^sin x', d:'●●○', i:['funcio-derivada/data/full-9.png']},
    119: {t:'Derivació logarítmica: xˣ, (1 + x²)ˣ, (sin x)^cos x, ˣ√(x³), (1 + 1/x)ˣ i (tg x)ˣ', d:'●●○', i:['funcio-derivada/data/full-9.png']},
    120: {t:'Derivació implícita de 3y − 4x² = 0 i comprovació amb la forma explícita', d:'●○○', i:['funcio-derivada/data/full-10.png']},
    121: {t:'Derivació implícita i explícita de x/3 − y/x = 6', d:'●●○', i:['funcio-derivada/data/full-10.png']},
    122: {t:'Repte: derivada implícita de x²+y²−2xy, x = cos(xy), x³+3y²−2ay i e^2y − ln x³', d:'●●●', i:['funcio-derivada/data/full-10.png']},
    123: {t:'Derivada de la funció inversa: arccos, arcsin, arctg, eˣ, ln x i x² − 2', d:'●●○', i:['funcio-derivada/data/full-10.png','funcio-derivada/data/full-11.png']},
    124: {t:'Investiga: cardioide (x²+y²−2ax)² − 4a²(x²+y²) = 0; tangents en x = 3 i x = 4', d:'●●●', i:['funcio-derivada/data/full-11.png']},
    125: {t:'Matemàtiques i… contaminació: a quina velocitat augmentarà la concentració de CO₂', d:'●●○', i:['problemes-contextualitzats/data/full-1.png']},
    126: {t:'Matemàtiques i… biologia: taxa de creixement de bacteris N(t) = 100·2,5^(0,7t)', d:'●●○', i:['problemes-contextualitzats/data/full-1.png','problemes-contextualitzats/data/full-2.png']},
    127: {t:'Matemàtiques i… química: llei de Boyle i variació de volum quan t = 10', d:'●●○', i:['problemes-contextualitzats/data/full-2.png']},
    128: {t:'Matemàtiques i… economia: cost marginal de C(x) = 350 + 2x + x²/2000', d:'●●○', i:['problemes-contextualitzats/data/full-2.png']},
    129: {t:'Matemàtiques i… física: posició, velocitat i acceleració de P(t) = e^(t−1)/t', d:'●●○', i:['problemes-contextualitzats/data/full-2.png']},
    130: {t:'Matemàtiques i… cinètica: velocitat i acceleració del projectil h(t) = 50t − 5t²', d:'●●○', i:['problemes-contextualitzats/data/full-2.png','problemes-contextualitzats/data/full-3.png']},
    131: {t:'f(x) = ∛(ln(x + 1) + x): calcula la derivada i troba f′(1) i f′(6)', d:'', i:['problemes-diferents/data/full-1.png']},
    132: {t:'W(t) = ∛(ln(t + 1) + t): la potència com a derivada del treball respecte del temps', d:'', i:['problemes-diferents/data/full-1.png']},
    133: {t:'Derivada de f(x) = abˣcos x i de g(x) = abˣsin x', d:'', i:['problemes-diferents/data/full-1.png']},
    134: {t:'Espiral àuria de posició (abᵗcos t, abᵗsin t): coordenades del vector velocitat', d:'', i:['problemes-diferents/data/full-1.png']},
    135: {t:'f(x) = a·sin(b·c − d·x + e): primera i segona derivada amb a, b, c, d i e constants', d:'', i:['problemes-diferents/data/full-1.png']},
    136: {t:'Ona harmònica y(x, t) = A·sin(kx − ωt + φ₀): velocitat i acceleració en cada instant', d:'', i:['problemes-diferents/data/full-1.png']},
  },

  'u9': {
      1: {t:'Diferència en superfície entre la llauna perfecta i la que es fabrica habitualment', d:'', i:['mon-real/data/full-1.png'], a:1},
      2: {t:'Poden existir altres mesures amb superfície mínima i el mateix contingut?', d:'', i:['mon-real/data/full-1.png'], a:1},
      3: {t:'Té una llauna de tomàquet triturat les mesures perquè sigui la més barata possible?', d:'', i:['mon-real/data/full-1.png'], a:1},
      4: {t:'Cost de fabricar la llauna perfecta i la normal, a 50 cèntims per m² de material', d:'', i:['mon-real/data/full-1.png'], a:1},
     30: {t:'f(x) = 2x³ + ax² + bx + c: troba a, b i c amb extrems a x = 1 i x = 2 i P(1, 6) a la gràfica', d:'', i:['practica/data/full-1.png']},
     31: {t:'f(x) = ax⁴ − 3x³ + 2x² − x: valor d\'a a partir del qual la funció és sempre convexa', d:'', i:['practica/data/full-1.png','practica/data/full-2.png']},
     32: {t:'Esbós de la gràfica de la derivada a partir de la gràfica de f a l\'interval (−3, 3)', d:'', i:['practica/data/full-2.png']},
     33: {t:'De tots els triangles rectangles d\'hipotenusa 5 m, troba el d\'àrea màxima', d:'', i:['practica/data/full-2.png']},
     34: {t:'Benefici d\'una empresa definit a trossos: quan es produeixen el màxim i el mínim?', d:'', i:['practica/data/full-2.png','practica/data/full-3.png']},
     35: {t:'Existeix c a [−2, 2] amb f′(c) = 0? Funció a trossos amb x² + x, x i 3cos(x − 3)', d:'', i:['practica/data/full-3.png']},
     36: {t:'Prova que f(x) = x³ + 2x i g(x) = x² − 1 es tallen en un únic punt', d:'', i:['practica/data/full-3.png','practica/data/full-4.png']},
     37: {t:'Calcula a i b perquè la funció a trossos compleixi el teorema del valor mitjà a [0, 4]', d:'', i:['practica/data/full-4.png']},
     38: {t:'Calcula a perquè dos límits amb indeterminació 0/0 valguin 4 i −1', d:'', i:['practica/data/full-4.png']},
     39: {t:'Quants extrems relatius pot tenir com a màxim una recta, una paràbola o un polinomi?', d:'●○○', i:['creixement/data/full-1.png','creixement/data/full-2.png']},
     40: {t:'A partir de f′(x), decideix si la funció és creixent o decreixent en cada punt', d:'●○○', i:['creixement/data/full-2.png']},
     41: {t:'A partir de la gràfica de f′(x), indica on f assoleix els màxims i els mínims', d:'●●○', i:['creixement/data/full-2.png']},
     42: {t:'Monotonia i extrems de quatre funcions polinòmiques', d:'●○○', i:['creixement/data/full-2.png','creixement/data/full-3.png']},
     43: {t:'Investiga: comprova que l\'abscissa del vèrtex d\'una paràbola és −b/2a', d:'●●●', i:['creixement/data/full-3.png']},
     44: {t:'Inventa: una funció amb un màxim en x = 2 i una altra amb un mínim en x = 5', d:'●●○', i:['creixement/data/full-3.png']},
     45: {t:'Monotonia i extrems de sis funcions polinòmiques, tres amb valor absolut', d:'●○○', i:['creixement/data/full-3.png','creixement/data/full-4.png']},
     46: {t:'Monotonia i extrems relatius de quatre funcions racionals', d:'●○○', i:['creixement/data/full-4.png']},
     47: {t:'Monotonia i extrems de quatre funcions logarítmiques', d:'●○○', i:['creixement/data/full-5.png']},
     48: {t:'Creixement de 2cos(x + π/2), x − sin x i arctg x, i existència d\'extrems', d:'●○○', i:['creixement/data/full-5.png']},
     49: {t:'Monotonia i extrems de sis funcions exponencials', d:'●●○', i:['creixement/data/full-5.png','creixement/data/full-6.png']},
     50: {t:'Màxims i mínims de sis funcions utilitzant la derivada segona', d:'●●○', i:['creixement/data/full-6.png','creixement/data/full-7.png']},
     51: {t:'Demostra que y = x³ − 2x² + 6x − 13 és sempre creixent', d:'●●○', i:['creixement/data/full-7.png']},
     52: {t:'Comprova que y = x⁵ + mx + 2 és creixent per a qualsevol valor positiu de m', d:'●●○', i:['creixement/data/full-7.png']},
     53: {t:'Demostra que y = 2x³ + x² + x − 1 talla l\'eix d\'abscisses en un sol punt', d:'●●●', i:['creixement/data/full-7.png']},
     54: {t:'A partir de la gràfica de f′: derivabilitat, monotonia, extrems i càlcul de f(2)', d:'●●○', i:['creixement/data/full-7.png']},
     55: {t:'y = ax² + bx + c: troba els coeficients amb dos punts i una recta tangent donada', d:'●●○', i:['creixement/data/full-8.png']},
     56: {t:'Investiga: quants mínims té una funció derivable amb exactament dos màxims?', d:'●●○', i:['creixement/data/full-8.png']},
     57: {t:'Beneficis B(x) = ax² + bx + c d\'una companyia de transport: determina a, b i c', d:'●●○', i:['creixement/data/full-8.png']},
     58: {t:'y = x³ + ax amb extrem relatiu a x = 2: troba a i estudia la monotonia', d:'●●○', i:['creixement/data/full-8.png']},
     59: {t:'Bacteris N(t) = −t² + at − b: troba a i b sabent que el màxim és a les 10 h', d:'●●○', i:['creixement/data/full-8.png','creixement/data/full-9.png']},
     60: {t:'f(x) = a²x/(2x² − 5ax + 2a²) amb extrem a x = 2: calcula a i el domini', d:'●●○', i:['creixement/data/full-9.png']},
     61: {t:'Calcula a, b i c perquè (x²+ax+b)/(x²+ax+c) tingui extrem a (2, −1) i passi per l\'origen', d:'●●●', i:['creixement/data/full-9.png']},
     62: {t:'y = x·e^(ax): valor de la constant a perquè hi hagi un màxim relatiu a x = 1', d:'●●○', i:['creixement/data/full-9.png']},
     63: {t:'Repte: f(x) = x + ax·|x| amb extrem a x = 1; monotonia i extrems relatius', d:'●●●', i:['creixement/data/full-9.png','creixement/data/full-10.png']},
     64: {t:'Matemàtiques i… empreses: funcions d\'ingrés i de guany, i intervals de creixement', d:'●●○', i:['creixement/data/full-10.png']},
     65: {t:'A partir de la gràfica de f′(x), indica on es troben els punts d\'inflexió de f', d:'●○○', i:['concavitat/data/full-1.png']},
     66: {t:'Quants punts d\'inflexió pot tenir una recta, una paràbola o un polinomi de grau n?', d:'●○○', i:['concavitat/data/full-1.png']},
     67: {t:'Curvatura de catorze funcions: racionals, radicals, logarítmiques i trigonomètriques', d:'●●○', i:['concavitat/data/full-1.png','concavitat/data/full-2.png','concavitat/data/full-3.png']},
     68: {t:'Inventa: representa una funció amb un punt d\'inflexió a x = 0', d:'●○○', i:['concavitat/data/full-3.png']},
     69: {t:'y = x³ + ax² − 3x: valor del paràmetre a perquè hi hagi inflexió a x = 1', d:'●○○', i:['concavitat/data/full-3.png']},
     70: {t:'Determina a, b i c amb pas per l\'origen, inflexió a x = −1 i pendent 3 a x = 1', d:'●●○', i:['concavitat/data/full-3.png']},
     71: {t:'Demostra que y = x⁴ + 3x² − 5x + 6 no té cap punt d\'inflexió', d:'●○○', i:['concavitat/data/full-3.png','concavitat/data/full-4.png']},
     72: {t:'Calcula a i b perquè x³ + ax² + bx + 7 tingui inflexió a x = 1 amb tangent a 45°', d:'●●○', i:['concavitat/data/full-4.png']},
     73: {t:'Polinomi de grau quatre sense terme en x³ amb P(0, 3), extrem a Q(1, 0) i inflexió a x = 1/2', d:'●●○', i:['concavitat/data/full-4.png']},
     74: {t:'y = x³ − ax² − 4x + b talla l\'eix OX a x = 3 i té inflexió a x = 2/3: troba a i b', d:'●●○', i:['concavitat/data/full-4.png']},
     75: {t:'Troba a perquè les tangents a y = ax⁴ + 2ax³ − ax + 1512 als punts d\'inflexió siguin perpendiculars', d:'●●●', i:['concavitat/data/full-4.png']},
     76: {t:'De tots els triangles rectangles amb catets que sumen 20 cm, el d\'àrea màxima', d:'●●●', i:['optimitzacio/data/full-1.png','optimitzacio/data/full-2.png']},
     77: {t:'Triangles rectangles de 8 cm d\'hipotenusa: quin té més àrea i quant mesura?', d:'●●○', i:['optimitzacio/data/full-2.png']},
     78: {t:'Investiga: rectangle d\'àrea màxima inscrit en un cercle de 6 cm de radi', d:'●●●', i:['optimitzacio/data/full-2.png']},
     79: {t:'Full de paper amb 18 cm² de text i marges donats: despesa de paper mínima', d:'●●○', i:['optimitzacio/data/full-2.png','optimitzacio/data/full-3.png']},
     80: {t:'Rectangle d\'àrea màxima inscrit en una semicircumferència de 5 cm de radi', d:'●●○', i:['optimitzacio/data/full-3.png']},
     81: {t:'De tots els prismes rectes de base quadrada i 24 cm² d\'àrea total, el de més volum', d:'●●●', i:['optimitzacio/data/full-3.png']},
     82: {t:'Cartolina de perímetre 60 cm que en girar genera un cilindre de volum màxim', d:'●●○', i:['optimitzacio/data/full-3.png','optimitzacio/data/full-4.png']},
     83: {t:'Triangle isòsceles de perímetre 10 m que en girar genera un con de volum màxim', d:'●●○', i:['optimitzacio/data/full-4.png']},
     84: {t:'Investiga: els cilindres amb igual volum tenen la mateixa superfície?', d:'●●○', i:['optimitzacio/data/full-4.png']},
     85: {t:'Repte: de tots els cons inscrits en una esfera de 9 cm de radi, el de més volum', d:'●●●', i:['optimitzacio/data/full-4.png']},
     86: {t:'Rectangles amb un vèrtex a la recta x + 2y = 2: el de més superfície', d:'●●○', i:['optimitzacio/data/full-5.png']},
     87: {t:'Determina els punts de la paràbola y = x² a mínima distància del punt (0, 1)', d:'●●●', i:['optimitzacio/data/full-5.png']},
     88: {t:'Quadrat i cercle amb perímetres que sumen 98 cm i suma d\'àrees mínima', d:'●●○', i:['optimitzacio/data/full-5.png']},
     89: {t:'Rectangle amb un vèrtex a la corba y = 1/x² + 4: determina el d\'àrea mínima', d:'●●○', i:['optimitzacio/data/full-6.png']},
     90: {t:'Matemàtiques i… recursos humans: quan programar les reunions segons la productivitat', d:'●●○', i:['optimitzacio/data/full-6.png']},
     91: {t:'Repte: recta per (2, 1) que forma amb els semieixos positius un triangle d\'àrea mínima', d:'●●●', i:['optimitzacio/data/full-6.png','optimitzacio/data/full-7.png']},
     92: {t:'Quina condició del teorema de Rolle falla en cadascuna de les quatre gràfiques?', d:'●○○', i:['teoremes/data/full-1.png']},
     93: {t:'Rolle aplicat a f(x) = x² + 2x − 3 a [−4, 2] i interpretació geomètrica', d:'●○○', i:['teoremes/data/full-1.png']},
     94: {t:'f(x) = x³ + x² − x − 1 satisfà Rolle a [−1, 1]: calcula el punt de la tesi', d:'●●○', i:['teoremes/data/full-1.png']},
     95: {t:'Inventa: dues funcions que compleixin el teorema de Rolle a [a, b]', d:'●●○', i:['teoremes/data/full-1.png']},
     96: {t:'Per què 1/x⁴ i 2 − |x| no contradiuen el teorema de Rolle a [−2, 2]?', d:'●●○', i:['teoremes/data/full-1.png','teoremes/data/full-2.png']},
     97: {t:'f(x) = 3cos²x verifica Rolle a [π/2, 3π/2]: calcula el valor de la tesi', d:'●○○', i:['teoremes/data/full-2.png']},
     98: {t:'Valors d\'a perquè f(x) = x³ − 7x compleixi Rolle a [1, a]; troba el punt', d:'●●○', i:['teoremes/data/full-2.png']},
     99: {t:'Determina a, b i c per aplicar Rolle a una funció a trossos a [0, 4]', d:'●●○', i:['teoremes/data/full-2.png','teoremes/data/full-3.png']},
    100: {t:'Investiga: valor del paràmetre per aplicar Rolle a [−√2, 2]; és màxim o mínim?', d:'●●○', i:['teoremes/data/full-3.png']},
    101: {t:'Demostra que l\'equació x + 1 = eˣ només té una solució', d:'●●●', i:['teoremes/data/full-3.png']},
    102: {t:'Demostra que x² = x·cos x − sin x es verifica per a un únic valor de x', d:'●●○', i:['teoremes/data/full-3.png','teoremes/data/full-4.png']},
    103: {t:'Demostra que f(x) = x³ − 3x + 1 només talla l\'eix X un cop a [0, 1]', d:'●●○', i:['teoremes/data/full-4.png']},
    104: {t:'x³ + 6x² + 15x + 9 = 0 té una única arrel: situa-la en un interval de longitud 1/2', d:'●●○', i:['teoremes/data/full-4.png']},
    105: {t:'Repte: calcula a, b i c perquè f(x) compleixi Rolle a [−2, c] i troba la tesi', d:'●●○', i:['teoremes/data/full-4.png']},
    106: {t:'Teorema del valor mitjà per a f(x) = −x² + 2x − 8 a [−3, 3] i interpretació', d:'●○○', i:['teoremes/data/full-4.png','teoremes/data/full-5.png']},
    107: {t:'És aplicable el teorema del valor mitjà a f(x) = x·ln x a l\'interval [0, e]?', d:'●●○', i:['teoremes/data/full-5.png']},
    108: {t:'f(x) = √|x − 7|: es pot aplicar el valor mitjà a [8, 10]? I a [6, 8]?', d:'●●○', i:['teoremes/data/full-5.png']},
    109: {t:'Punt de y = x² entre A(1, 1) i B(3, 9) amb tangent paral·lela a la corda AB', d:'●●○', i:['teoremes/data/full-5.png','teoremes/data/full-6.png']},
    110: {t:'Determina a i b per poder aplicar el teorema del valor mitjà a [−1, 3]', d:'●○○', i:['teoremes/data/full-6.png']},
    111: {t:'Troba a i b per poder aplicar el teorema del valor mitjà a [3, 5]', d:'●●○', i:['teoremes/data/full-6.png']},
    112: {t:'Calcula a i b per aplicar el valor mitjà a [−2, 2] i troba el punt de la tesi', d:'●●○', i:['teoremes/data/full-6.png','teoremes/data/full-7.png']},
    113: {t:'Determina a i b per aplicar el teorema de Lagrange a [−1, π/2]', d:'●●○', i:['teoremes/data/full-7.png','teoremes/data/full-8.png']},
    114: {t:'Determina a i b per aplicar el teorema de Lagrange a [−2, π/2] i troba el punt', d:'●●○', i:['teoremes/data/full-8.png']},
    115: {t:'Sis límits del tipus 0/0 amb polinomis i radicals', d:'●●○', i:['hopital/data/full-1.png','hopital/data/full-2.png']},
    116: {t:'Sis límits trigonomètrics indeterminats amb sinus, cosinus i tangent', d:'●●○', i:['hopital/data/full-2.png','hopital/data/full-3.png']},
    117: {t:'Quatre límits amb logaritmes: ln(eˣ + x³)/x, ln(cos 3x)/x² i similars', d:'●●○', i:['hopital/data/full-3.png']},
    118: {t:'Quatre límits amb exponencials, alguns amb paràmetres', d:'●●○', i:['hopital/data/full-3.png','hopital/data/full-4.png']},
    119: {t:'Quatre límits del tipus 1^∞ resolts prenent logaritmes', d:'●●○', i:['hopital/data/full-4.png']},
    120: {t:'Quatre límits del tipus 0⁰: xˣ, (3x)^(2sin x), x^tg x i (cotg x)^sin x', d:'●●○', i:['hopital/data/full-4.png','hopital/data/full-5.png']},
    121: {t:'Dos límits del tipus ∞ − ∞ amb logaritmes i sinus', d:'●●○', i:['hopital/data/full-5.png']},
    122: {t:'Quatre límits del tipus 0·∞ amb exponencials, arrels i tangent', d:'●●○', i:['hopital/data/full-5.png','hopital/data/full-6.png']},
    123: {t:'Quatre límits 0·∞ amb funcions trigonomètriques i les seves inverses', d:'●●○', i:['hopital/data/full-6.png','hopital/data/full-7.png']},
    124: {t:'Dos límits quan x → +∞: (ln x)^(e⁻ˣ) i (1 + tg(1/x))ˣ', d:'●●○', i:['hopital/data/full-7.png']},
    125: {t:'Tres límits amb composicions de sinus, tangent i arctangent', d:'●●○', i:['hopital/data/full-7.png','hopital/data/full-8.png']},
    126: {t:'Troba m sabent que dos límits són finits i determina\'n el valor', d:'●●○', i:['hopital/data/full-8.png']},
    127: {t:'Valor del paràmetre μ que fa finit el límit, i resolució del límit', d:'●●○', i:['hopital/data/full-8.png','hopital/data/full-9.png']},
    128: {t:'Repte: calcula a i b perquè (ax² + bx + 1 − cos x)/sin(x²) valgui 1', d:'●●●', i:['hopital/data/full-9.png']},
    129: {t:'Caldera d\'un institut: determina a i b del consum C(t) = (t − a)² + b', d:'●○○', i:['aplicacions/data/full-1.png']},
    130: {t:'Matemàtiques i… biologia: moment ideal per afegir bactericides al llac', d:'●○○', i:['aplicacions/data/full-1.png','aplicacions/data/full-2.png']},
    131: {t:'Matemàtiques i… física: quan és mínima la velocitat i quan s\'anul·la l\'acceleració', d:'●●○', i:['aplicacions/data/full-2.png']},
    132: {t:'Matemàtiques i… poblacions: població màxima de mosques N(t) = −(t − 2)² + 9', d:'●●○', i:['aplicacions/data/full-2.png']},
    133: {t:'Escenari rectangular de 100 m² amb perímetre mínim: llargada i amplada', d:'●●○', i:['aplicacions/data/full-2.png']},
    134: {t:'Matemàtiques i… construcció: dimensions d\'una finestra de 2 m² amb marc mínim', d:'●●○', i:['aplicacions/data/full-2.png','aplicacions/data/full-3.png']},
    135: {t:'Finestra de perímetre 6 m amb capçal a 90°: valors d\'a i b per a màxima lluminositat', d:'●●○', i:['aplicacions/data/full-3.png']},
    136: {t:'Dipòsit obert de 20 m³ i base quadrada amb revestiment de cost mínim', d:'●●○', i:['aplicacions/data/full-3.png']},
    137: {t:'Tanc cilíndric amb semiesferes als extrems: dimensions de cost mínim', d:'●●○', i:['aplicacions/data/full-3.png','aplicacions/data/full-4.png']},
    138: {t:'f(x) = e^(−x+1)·sin x + 1 a [1, 6]: coordenades del màxim i del mínim', d:'', i:['problemes-diferents/data/full-1.png']},
    139: {t:'Consum d\'aigua d\'un centre de salut: mesos de consum màxim i mínim', d:'', i:['problemes-diferents/data/full-1.png']},
    140: {t:'f(x) = 50 + x i g(x) = 800 − 10x: comprova que h(x) = f(x)·g(x) té un màxim', d:'', i:['problemes-diferents/data/full-1.png']},
    141: {t:'Hort amb 50 pomeres: quants arbres més cal plantar per a la producció màxima?', d:'', i:['problemes-diferents/data/full-2.png']},
    142: {t:'f(x) = x·g(x) amb g(x) = 1000 − 2x: valor de x on f assoleix el màxim', d:'', i:['problemes-diferents/data/full-2.png']},
    143: {t:'Pastor amb 1000 m de tela metàl·lica i una paret: tanca de superfície màxima', d:'', i:['problemes-diferents/data/full-2.png']},
  },

  'u10': {
      1: {t:'Explica amb les teves paraules el procés exposat', d:'', i:['mon-real/data/full-1.png'], a:1},
      2: {t:'Punts intermedis en una ampliació a 32 vegades la mida original', d:'', i:['mon-real/data/full-1.png'], a:1},
      3: {t:'Donats dos punts del pla, la recta és l’única funció que hi passa?', d:'', i:['mon-real/data/full-2.png'], a:1},
      4: {t:'Quants punts calen com a mínim per determinar una funció polinòmica de grau n?', d:'', i:['mon-real/data/full-2.png'], a:1},
     34: {t:'Determina el domini de f(x) = ln √(1/(x+2))', d:'', i:['practica/data/full-1.png','practica/data/full-2.png']},
     35: {t:'Estudia la simetria de f(x) = 5·ln(√(x²+1))/(x²+2)', d:'', i:['practica/data/full-2.png']},
     36: {t:'y = 2x − 1 és asímptota obliqua de f(x) = (2x²−1)/(x+k): troba k', d:'', i:['practica/data/full-2.png']},
     37: {t:'Donada la gràfica de f′(x), estudia les característiques de f(x)', d:'', i:['practica/data/full-2.png']},
     38: {t:'Representa una funció amb domini ℝ−{1}, asímptota vertical x = 1 i obliqua y = x+1', d:'', i:['practica/data/full-2.png']},
     39: {t:'f(x) = ax³ + bx + 1 té un extrem relatiu a (1, 0): calcula a i b', d:'', i:['practica/data/full-2.png']},
     40: {t:'Representa gràficament f(x) = x²e⁻ˣ i f(x) = x·ln x − x', d:'', i:['practica/data/full-2.png','practica/data/full-3.png']},
     41: {t:'Representa f(x) = x/(x²−1)', d:'', i:['practica/data/full-4.png']},
     42: {t:'Estudia i representa la funció trigonomètrica f(x) = 2cos(3x − π) + 1', d:'', i:['practica/data/full-4.png','practica/data/full-5.png']},
     43: {t:'Domini de sis funcions: racional, radical, exponencial, logarítmica i trigonomètrica', d:'●○○', i:['domini-recorregut/data/full-1.png']},
     44: {t:'INVENTA. Escriu dues funcions amb cadascun d’aquests quatre dominis', d:'●○○', i:['domini-recorregut/data/full-1.png']},
     45: {t:'Domini i punts de tall amb els eixos de quatre funcions polinòmiques i racionals', d:'●○○', i:['domini-recorregut/data/full-1.png']},
     46: {t:'Domini i punts de tall de quatre funcions amb radicals', d:'●○○', i:['domini-recorregut/data/full-1.png','domini-recorregut/data/full-2.png']},
     47: {t:'Domini i punts de tall de quatre funcions exponencials', d:'●●○', i:['domini-recorregut/data/full-2.png']},
     48: {t:'Domini de quatre funcions logarítmiques', d:'●●○', i:['domini-recorregut/data/full-2.png']},
     49: {t:'Domini de quatre funcions trigonomètriques: sin, tg i arccos', d:'●●○', i:['domini-recorregut/data/full-2.png','domini-recorregut/data/full-3.png']},
     50: {t:'En quins punts no estan definides quatre funcions del tipus √(a ± x)/(9 − x²)', d:'●○○', i:['domini-recorregut/data/full-3.png']},
     51: {t:'Domini de quatre funcions que combinen radicals, quocients i logaritmes', d:'●●○', i:['domini-recorregut/data/full-3.png']},
     52: {t:'REPTE. Domini de quatre funcions amb valor absolut, exponencials i radicals', d:'●●●', i:['domini-recorregut/data/full-3.png','domini-recorregut/data/full-4.png']},
     53: {t:'INVESTIGA. Valor de m perquè la funció a trossos amb tg x / x estigui definida a tot ℝ', d:'●●●', i:['domini-recorregut/data/full-4.png']},
     54: {t:'Simetria respecte de l’eix d’ordenades o de l’origen: x²+1, x³−x, x⁴−x²+4', d:'●●○', i:['simetria-periodicitat/data/full-1.png']},
     55: {t:'Simetria parella o imparella de quatre funcions, una de logarítmica', d:'●○○', i:['simetria-periodicitat/data/full-1.png']},
     56: {t:'Domini, punts de tall i simetria de sis funcions racionals, exponencials i radicals', d:'●○○', i:['simetria-periodicitat/data/full-1.png','simetria-periodicitat/data/full-2.png']},
     57: {t:'Periodicitat de 2sin x, sin(2x), 2tg x i tg(2x)', d:'●●○', i:['simetria-periodicitat/data/full-2.png']},
     58: {t:'INVESTIGA. Pot una funció tenir simetria que no sigui parella ni imparella?', d:'●●○', i:['simetria-periodicitat/data/full-2.png','simetria-periodicitat/data/full-3.png']},
     59: {t:'Període de sis funcions: cos(3x), sin²x, sin(2x)cos(3x), 3cos x, sin(x−π/4), x²−sin²x', d:'●●○', i:['simetria-periodicitat/data/full-3.png']},
     60: {t:'INVENTA. Una funció racional amb simetria parella i una altra amb simetria imparella', d:'●○○', i:['simetria-periodicitat/data/full-3.png']},
     61: {t:'Escriu les equacions de les asímptotes a partir de dues gràfiques', d:'●●○', i:['asimptotes/data/full-1.png']},
     62: {t:'Branques infinites i asímptotes de quatre funcions polinòmiques', d:'●○○', i:['asimptotes/data/full-2.png']},
     63: {t:'Asímptotes i branques infinites de quatre funcions racionals', d:'●○○', i:['asimptotes/data/full-2.png']},
     64: {t:'Asímptotes de quatre funcions amb radicals', d:'●●○', i:['asimptotes/data/full-2.png','asimptotes/data/full-3.png']},
     65: {t:'Asímptotes de quatre funcions logarítmiques', d:'●●○', i:['asimptotes/data/full-3.png','asimptotes/data/full-4.png']},
     66: {t:'INVENTA. Dibuixa una gràfica amb asímptota vertical x = −2 i horitzontal y = 2', d:'●○○', i:['asimptotes/data/full-4.png']},
     67: {t:'Justifica si quatre funcions amb indeterminació 0/0 tenen asímptotes verticals', d:'●●●', i:['asimptotes/data/full-4.png','asimptotes/data/full-5.png']},
     68: {t:'REPTE. Hi ha asímptota horitzontal? 4xe⁻ˣ, 3xe^(1/x), 2x(ˣ√e−3), 3x·arctg(3/x)', d:'●●●', i:['asimptotes/data/full-5.png']},
     69: {t:'INVESTIGA. Quantes asímptotes obliqües pot tenir una funció com a màxim?', d:'●●○', i:['asimptotes/data/full-5.png']},
     70: {t:'Troba a i b perquè (ax²+3x−2)/(bx+5) tingui asímptota horitzontal y = 3 o obliqua y = x+2', d:'●●○', i:['asimptotes/data/full-5.png','asimptotes/data/full-6.png']},
     71: {t:'Simetria i asímptotes de f(x) = x²/(9 − x²)', d:'●○○', i:['asimptotes/data/full-6.png']},
     72: {t:'Simetria i asímptotes de f(x) = −x³/(x² − 4)', d:'●○○', i:['asimptotes/data/full-6.png']},
     73: {t:'Simetria i asímptotes de f(x) = x·e^(−x²) i f(x) = ½·ln|x|', d:'●●○', i:['asimptotes/data/full-6.png']},
     74: {t:'REPTE. Demostra que f(x) = a·sin x / x no té asímptota vertical per a cap valor d’a', d:'●●●', i:['asimptotes/data/full-7.png']},
     75: {t:'Intervals de creixement i decreixement i extrems relatius de sis funcions', d:'●○○', i:['creixement/data/full-1.png','creixement/data/full-2.png']},
     76: {t:'Creixement, decreixement i extrems de √(x²−2x), ln x/x², (x+4)/(x−4) i x²/3ˣ', d:'●●○', i:['creixement/data/full-2.png']},
     77: {t:'Creixement i extrems relatius de f(x) = (4x + 2x²)/eˣ', d:'●●○', i:['creixement/data/full-2.png','creixement/data/full-3.png']},
     78: {t:'Intervals de concavitat i convexitat i punts d’inflexió de quatre funcions', d:'●○○', i:['concavitat/data/full-1.png']},
     79: {t:'Concavitat, convexitat i punts d’inflexió de x²eˣ, x/ln x, x − sin x i √(x²−16)', d:'●●○', i:['concavitat/data/full-1.png','concavitat/data/full-2.png']},
     80: {t:'Estudi complet de f(x) = x²/(x²−1) i g(x) = (x+1)/x²', d:'●○○', i:['estudi-complet/data/full-1.png','estudi-complet/data/full-2.png']},
     81: {t:'Monotonia, curvatura i recta tangent al punt d’inflexió de f(x) = x³ − 9x² + 18x', d:'●●○', i:['estudi-complet/data/full-2.png']},
     82: {t:'Classifica l’extrem relatiu donat i estudia la monotonia i la curvatura de tres funcions', d:'●○○', i:['estudi-complet/data/full-2.png','estudi-complet/data/full-3.png']},
     83: {t:'INVESTIGA. f(x) = x³+ax²+bx+c amb extrem a P(1,0) i inflexió a x = 4/3: monotonia i curvatura', d:'●○○', i:['estudi-complet/data/full-3.png']},
     84: {t:'Estudia i representa set funcions polinòmiques', d:'●○○', i:['representacio/data/full-1.png','representacio/data/full-2.png','representacio/data/full-3.png','representacio/data/full-4.png','representacio/data/full-5.png']},
     85: {t:'Dibuixa la gràfica de quatre funcions polinòmiques de tercer i quart grau', d:'●○○', i:['representacio/data/full-5.png','representacio/data/full-6.png','representacio/data/full-7.png']},
     86: {t:'INVENTA. Representa una polinòmica a partir dels límits, la derivada i els punts de tall', d:'●●○', i:['representacio/data/full-7.png']},
     87: {t:'f(x) = x³ + ax amb extrem relatiu a x = 2√3/3: estudi complet i representació', d:'●●○', i:['representacio/data/full-7.png','representacio/data/full-8.png']},
     88: {t:'Troba a, b i c de x³+ax²+bx+c amb extrem a x = 2, inflexió a x = 0 i pas per (1,−5)', d:'●●○', i:['representacio/data/full-8.png']},
     89: {t:'Estudi complet i representació de f(x) = 3x²/(x² − 1)', d:'●○○', i:['representacio/data/full-8.png','representacio/data/full-9.png']},
     90: {t:'MATEMÀTIQUES I... OCI. El tobogan f(x) = (−2x²+x+1)/(2(x+1)) + 5', d:'●●○', i:['representacio/data/full-9.png']},
     91: {t:'Estudi complet i representació de f(x) = x³/(x² − 4)', d:'●○○', i:['representacio/data/full-9.png','representacio/data/full-10.png']},
     92: {t:'Estudia i representa (x²−1)/x, x/(x²−1), (4−x²)/x i x³/(x²−1)', d:'●○○', i:['representacio/data/full-10.png','representacio/data/full-11.png','representacio/data/full-12.png','representacio/data/full-13.png']},
     93: {t:'Representa quatre funcions racionals del tipus (x²−a)/(b−x²)', d:'●○○', i:['representacio/data/full-13.png','representacio/data/full-14.png','representacio/data/full-15.png']},
     94: {t:'Esbós de les gràfiques de x/(x+2), x²/(x+2), x³/(x+2) i x³/(x+2)²', d:'●○○', i:['representacio/data/full-15.png','representacio/data/full-16.png','representacio/data/full-17.png']},
     95: {t:'Dibuixa la gràfica de (x−1)/x², (x−2)/(x−3), x²/(x+1) i x/(x²+1)', d:'●●○', i:['representacio/data/full-18.png','representacio/data/full-19.png','representacio/data/full-20.png']},
     96: {t:'INVESTIGA. f(x) = (x²−4)/(x+2): valor d’a, asímptota vertical i representació', d:'●●○', i:['representacio/data/full-20.png']},
     97: {t:'INVENTA. Representa una funció racional sempre decreixent amb asímptota horitzontal y = 1', d:'●●○', i:['representacio/data/full-20.png','representacio/data/full-21.png']},
     98: {t:'Representa una racional amb extrems a (−1,−4) i (1,4) i asímptota obliqua y = 2x', d:'●●○', i:['representacio/data/full-21.png']},
     99: {t:'MATEMÀTIQUES I... ECONOMIA. Interval d’utilitat i punt de saturació de f(x) = x − x²', d:'●●○', i:['representacio/data/full-21.png']},
    100: {t:'Dibuixa la gràfica de quatre funcions amb radicals', d:'●●○', i:['altres-funcions/data/full-1.png','altres-funcions/data/full-2.png']},
    101: {t:'Estudi i esbós de f(x) = √(x²+3x) − x i g(x) = √(x²+3x) − 2x', d:'●●○', i:['altres-funcions/data/full-2.png','altres-funcions/data/full-3.png','altres-funcions/data/full-4.png']},
    102: {t:'Dibuixa xeˣ, (e⁻ˣ+eˣ)/2, 3x²e⁻ˣ, (x²−1)/e^(x³), sin(x−π/4) i x²−sin²x', d:'●●○', i:['altres-funcions/data/full-4.png','altres-funcions/data/full-5.png','altres-funcions/data/full-6.png','altres-funcions/data/full-7.png']},
    103: {t:'Dibuixa x·ln x, ln((eˣ+e⁻ˣ)/2), log₂(x²+1) i x/ln x', d:'●●○', i:['altres-funcions/data/full-7.png','altres-funcions/data/full-8.png','altres-funcions/data/full-9.png']},
    104: {t:'Dibuixa e^(2/x), ½x²e⁻ˣ, 2xe⁻ˣ i (x−2)²eˣ', d:'●●○', i:['altres-funcions/data/full-9.png','altres-funcions/data/full-10.png','altres-funcions/data/full-11.png']},
    105: {t:'Beneficis d’una empresa amb f(x) = 2^(x/4) − ax/4: valor inicial, creixement i pèrdues', d:'●●○', i:['altres-funcions/data/full-11.png','altres-funcions/data/full-12.png']},
    106: {t:'f(x) = a + ln(x²−1) que passa per (√2, 1): paràmetre, asímptotes, monotonia i gràfica', d:'●●○', i:['altres-funcions/data/full-12.png']},
    107: {t:'REPTE. f(x) = 1 + a·sin(x/2) que passa per (π/2, 3): calcula a i representa-la', d:'●●●', i:['altres-funcions/data/full-13.png']},
    108: {t:'Estudia i representa quatre funcions definides a trossos', d:'●●○', i:['trossos/data/full-1.png','trossos/data/full-2.png','trossos/data/full-3.png']},
    109: {t:'INVENTA. Una funció amb valor absolut, expressada a trossos i representada', d:'●○○', i:['trossos/data/full-3.png']},
    110: {t:'Troba a i b perquè una funció a trossos amb arrel sigui contínua, i representa-la', d:'●●○', i:['trossos/data/full-3.png','trossos/data/full-4.png']},
    111: {t:'Muntanya russa: troba a perquè la trajectòria a trossos tingui sentit i estudia l’altura', d:'●●○', i:['trossos/data/full-4.png']},
    112: {t:'MATEMÀTIQUES I... ENGINYERIA. Traçat d’una carretera sense pics: troba a i b', d:'●●○', i:['trossos/data/full-4.png','trossos/data/full-5.png']},
    113: {t:'Estudia i representa quatre funcions amb valor absolut', d:'●●○', i:['trossos/data/full-5.png','trossos/data/full-6.png']},
    114: {t:'Derivabilitat, monotonia i gràfica de f(x) = x² − 5|x| + 6', d:'●●○', i:['trossos/data/full-6.png']},
    115: {t:'REPTE. Derivabilitat d’una funció a trossos i teorema de Lagrange a [−1, 3]', d:'●●●', i:['trossos/data/full-6.png','trossos/data/full-7.png']},
    116: {t:'MATEMÀTIQUES I... BIOLOGIA. Creixement logístic d’una població d’aus i perill d’extinció', d:'●●○', i:['problemes-reals/data/full-1.png']},
    117: {t:'MATEMÀTIQUES I... FARMÀCIA. Concentració d’un medicament en sang: màxim i posologia', d:'●●○', i:['problemes-reals/data/full-2.png']},
    118: {t:'MATEMÀTIQUES I... MEDICINA. Velocitat de la tos: radi de l’objecte per a velocitat màxima', d:'●●○', i:['problemes-reals/data/full-2.png']},
    119: {t:'Estudi de f(x) = (x²−10x+21)/20 en [1, 12]: talls, signe, monotonia, extrems i recorregut', d:'', i:['problemes-diferents/data/full-1.png','problemes-diferents/data/full-2.png']},
    120: {t:'La mateixa funció com a taxa d’inflació mensual d’un país durant el 2022', d:'', i:['problemes-diferents/data/full-2.png']},
    121: {t:'Estudi de f(x) = 10 − 5x − 5e^(−2x): tall amb l’eix Y, màxim, f′(1) i arrel per Bolzano', d:'', i:['problemes-diferents/data/full-2.png','problemes-diferents/data/full-3.png']},
    122: {t:'La mateixa funció com a altura d’un objecte llançat: altura inicial, màxim i velocitat', d:'', i:['problemes-diferents/data/full-3.png']},
    123: {t:'Estudi de f(x) = 20 + (5x−15)/(x²−6x+10): talls, signe, monotonia, extrems i recorregut', d:'', i:['problemes-diferents/data/full-3.png','problemes-diferents/data/full-4.png']},
    124: {t:'La mateixa funció com a temperatura d’una peça: valor inicial, límit i extrems', d:'', i:['problemes-diferents/data/full-4.png']},
  },
};

/* ── Consulta ─────────────────────────────────────────────────────────── */
function fitxaDe(u, n){
  const c = CATALEG[u]; return (c && c[n]) ? c[n] : null;
}
function etiquetaDe(u, n){
  const f = fitxaDe(u, n);
  return (f && f.a) ? 'Act. ' + n : 'Ex. ' + n;
}
function pistaDe(u, n){
  const f = fitxaDe(u, n);
  return (f && f.p) ? f.p : null;
}
